[general]
import = [
"~/.config/alacritty/catppuccin_mocha.toml"
]

[font]
size = 14

[font.normal]
family = "Hack Nerd Font"
style = "Medium"

[terminal.shell]
program = "/bin/bash"

[window]
opacity = 1.000000

[window.padding]
x = 20
y = 20
