[colors.primary]
background = '#2d353b'
foreground = '#d3c6aa'

[colors.normal]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

[colors.bright]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

[font]
size = 14

[font.normal]
family = "Hack Nerd Font"
style = "Medium"

[terminal.shell]
program = "/bin/bash"

[window]
opacity = 1.000000

[window.padding]
x = 20
y = 20
